import { CleanerItem, CleanerSummary, CleanerCategory } from './appCleanerTypes';

export function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

export const INITIAL_AUDIT_ITEMS: CleanerItem[] = [
  {
    id: 'adobe-media-cache',
    name: 'Adobe Media Cache Files',
    category: 'media-cache',
    safety: 'safe',
    path: 'AppData\\Roaming\\Adobe\\Common\\Media Cache Files',
    sizeBytes: 7162238976, // ~6.83 GB
    sizeFormatted: '6.83 GB',
    fileCount: 4210,
    lastModified: '2026-09-18',
    description: 'Rendered video and conformed audio scratch files for Premiere Pro & Media Encoder.',
    recommendation: '100% safe. Automatically regenerated by Adobe if an active project needs them.',
    selected: true,
  },
  {
    id: 'vscode-insiders-old-builds',
    name: 'VS Code Insiders Stale Update Builds',
    category: 'updates',
    safety: 'caution',
    path: 'AppData\\Local\\Programs\\Microsoft VS Code Insiders',
    sizeBytes: 6335102976, // ~5.90 GB redundant
    sizeFormatted: '5.90 GB',
    fileCount: 14820,
    lastModified: '2026-07-30',
    description: '8 obsolete commit build folders (e.g. 018354..., 29215b...) retained from older updates.',
    recommendation: 'Safe to remove old commit directories. Only the latest build is active.',
    selected: true,
  },
  {
    id: 'wps-office-old-version',
    name: 'WPS Office Inactive Version 12.1.0.28032',
    category: 'updates',
    safety: 'caution',
    path: 'AppData\\Local\\Kingsoft\\WPS Office\\12.1.0.28032',
    sizeBytes: 1670732800, // ~1.59 GB
    sizeFormatted: '1.59 GB',
    fileCount: 3120,
    lastModified: '2026-06-18',
    description: 'Previous complete installation directory kept after updating to version 12.1.0.28485.',
    recommendation: 'Safe to delete. The system is running active version 12.1.0.28485.',
    selected: true,
  },
  {
    id: 'playwright-old-browsers',
    name: 'Playwright Test Browser Binaries',
    category: 'dev-tools',
    safety: 'caution',
    path: 'AppData\\Local\\ms-playwright',
    sizeBytes: 1422794752, // ~1.35 GB
    sizeFormatted: '1.35 GB',
    fileCount: 1890,
    lastModified: '2026-09-14',
    description: 'Redundant Chromium build revisions (chromium-1208 and headless shells).',
    recommendation: 'Can be removed. Playwright will download current binaries if tests are rerun.',
    selected: false,
  },
  {
    id: 'pnpm-store-cache',
    name: 'pnpm Package Store',
    category: 'dev-tools',
    safety: 'safe',
    path: 'AppData\\Local\\pnpm\\store',
    sizeBytes: 1061158912, // ~1.01 GB
    sizeFormatted: '1.01 GB',
    fileCount: 53465,
    lastModified: '2026-09-13',
    description: 'Unindexed global package store containing cached node packages.',
    recommendation: 'Safe to prune using pnpm store prune or cleaner.',
    selected: true,
  },
  {
    id: 'vscode-insiders-vsix-cache',
    name: 'VS Code Insiders Cached Extension VSIXs',
    category: 'updates',
    safety: 'safe',
    path: 'AppData\\Roaming\\Code - Insiders\\CachedExtensionVSIXs',
    sizeBytes: 937459712, // ~894 MB
    sizeFormatted: '894 MB',
    fileCount: 42,
    lastModified: '2026-07-28',
    description: 'Cached extension package archives downloaded during past extension updates.',
    recommendation: '100% safe. Installed extensions are stored elsewhere in the extensions directory.',
    selected: true,
  },
  {
    id: 'vscode-stable-old-build',
    name: 'VS Code (Stable) Old Build 1b6a188127',
    category: 'updates',
    safety: 'caution',
    path: 'AppData\\Local\\Programs\\Microsoft VS Code\\1b6a188127',
    sizeBytes: 765460480, // ~730 MB
    sizeFormatted: '730 MB',
    fileCount: 2450,
    lastModified: '2026-07-27',
    description: 'Old commit build folder remaining alongside the current September build 08d4889f9e.',
    recommendation: 'Safe to remove old build directory. Active executable uses 08d4889f9e.',
    selected: true,
  },
  {
    id: 'cursor-backup-folder',
    name: 'Cursor Editor Update Backup (_)',
    category: 'updates',
    safety: 'safe',
    path: 'AppData\\Local\\Programs\\cursor\\_',
    sizeBytes: 734003200, // ~700 MB
    sizeFormatted: '700 MB',
    fileCount: 1840,
    lastModified: '2026-04-24',
    description: 'Backup copy of old binaries generated by auto-updater during an upgrade.',
    recommendation: 'Safe to delete. The current Cursor executable runs from the main directory.',
    selected: true,
  },
  {
    id: 'lm-studio-updater',
    name: 'LM Studio Staged Updater Packages',
    category: 'installers',
    safety: 'safe',
    path: 'AppData\\Local\\lm-studio-updater',
    sizeBytes: 663605248, // ~632.8 MB
    sizeFormatted: '632.8 MB',
    fileCount: 18,
    lastModified: '2026-08-31',
    description: 'Downloaded installer.exe and pending update packages stored after upgrade.',
    recommendation: '100% safe to remove. Future updates will download afresh if needed.',
    selected: true,
  },
  {
    id: 'adobe-telemetry-cache',
    name: 'Adobe Dunamis IPC & Telemetry Cache',
    category: 'media-cache',
    safety: 'safe',
    path: 'AppData\\Roaming\\com.adobe.dunamis',
    sizeBytes: 627195904, // ~598 MB
    sizeFormatted: '598 MB',
    fileCount: 120,
    lastModified: '2026-09-18',
    description: 'Adobe telemetry database and inter-process communication cache files.',
    recommendation: 'Safe to clear. Does not contain any user project files or preferences.',
    selected: true,
  },
  {
    id: 'aionui-orphaned',
    name: 'AionUi Abandoned App Data',
    category: 'orphaned',
    safety: 'safe',
    path: 'AppData\\Roaming\\AionUi',
    sizeBytes: 557121536, // ~531.3 MB
    sizeFormatted: '531.3 MB',
    fileCount: 650,
    lastModified: '2026-06-12',
    description: 'Remnant directory of uninstalled or inactive Electron application.',
    recommendation: 'Safe to delete. Software is not registered in Windows Apps registry.',
    selected: true,
  },
  {
    id: 'adobe-ptx-peaks',
    name: 'Adobe Peak & PTX Audio Waveform Caches',
    category: 'media-cache',
    safety: 'safe',
    path: 'AppData\\Roaming\\Adobe\\Common\\Peak Files & PTX',
    sizeBytes: 502534144, // ~479 MB
    sizeFormatted: '479 MB',
    fileCount: 1150,
    lastModified: '2026-09-18',
    description: 'Pre-computed audio display peaks and project playback translation caches.',
    recommendation: 'Safe to clean. Automatically recalculated on-demand.',
    selected: true,
  },
  {
    id: 'npm-cache',
    name: 'npm Global Cache',
    category: 'dev-tools',
    safety: 'safe',
    path: 'AppData\\Local\\npm-cache',
    sizeBytes: 421527552, // ~402 MB
    sizeFormatted: '402 MB',
    fileCount: 31770,
    lastModified: '2026-09-19',
    description: 'Stored package tarballs from historical npm install commands.',
    recommendation: 'Safe to clear. Equivalent to running npm cache clean --force.',
    selected: true,
  },
  {
    id: 'neo-compiler-cache',
    name: 'NEO Compiler Scratch Cache',
    category: 'orphaned',
    safety: 'safe',
    path: 'AppData\\Local\\NEO',
    sizeBytes: 415531008, // ~396.3 MB
    sizeFormatted: '396.3 MB',
    fileCount: 890,
    lastModified: '2026-07-23',
    description: 'Cached intermediate build objects for inactive compiler tool.',
    recommendation: 'Safe to delete.',
    selected: true,
  },
  {
    id: 'antigravity-updater',
    name: 'Antigravity Updater Installer Cache',
    category: 'installers',
    safety: 'safe',
    path: 'AppData\\Local\\antigravity-updater',
    sizeBytes: 300023808, // ~286.1 MB
    sizeFormatted: '286.1 MB',
    fileCount: 12,
    lastModified: '2026-09-19',
    description: 'Staged update installer binaries in local user cache.',
    recommendation: 'Safe to remove.',
    selected: true,
  },
  {
    id: 'windows-user-temp',
    name: 'Windows User Temp Directory',
    category: 'temp',
    safety: 'safe',
    path: 'AppData\\Local\\Temp',
    sizeBytes: 74973184, // ~71.5 MB
    sizeFormatted: '71.5 MB',
    fileCount: 183,
    lastModified: '2026-09-19',
    description: 'Temporary files created by running programs, installers, and web tools.',
    recommendation: '100% safe. In-use files are skipped automatically.',
    selected: true,
  }
];

export function calculateSummary(items: CleanerItem[]): CleanerSummary {
  let totalBytes = 0;
  let safeBytes = 0;
  let cautionBytes = 0;
  let selectedBytes = 0;
  let selectedCount = 0;

  for (const item of items) {
    totalBytes += item.sizeBytes;
    if (item.safety === 'safe') {
      safeBytes += item.sizeBytes;
    } else if (item.safety === 'caution') {
      cautionBytes += item.sizeBytes;
    }
    if (item.selected) {
      selectedBytes += item.sizeBytes;
      selectedCount += 1;
    }
  }

  return {
    totalBytes,
    totalFormatted: formatBytes(totalBytes),
    safeBytes,
    safeFormatted: formatBytes(safeBytes),
    cautionBytes,
    cautionFormatted: formatBytes(cautionBytes),
    itemCount: items.length,
    selectedBytes,
    selectedFormatted: formatBytes(selectedBytes),
    selectedCount
  };
}
